import React from 'react';
import { useNavigate } from 'react-router-dom';
import Logo from '../components/Logo';

export default function Privacy() {
    const navigate = useNavigate();

    return (
        <div className="min-h-screen bg-[var(--color-bg)] text-[var(--color-text)] font-sans p-8 md:p-16 transition-colors duration-300">
            <div className="max-w-4xl mx-auto">
                <div className="mb-12 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <Logo className="h-10" textColor="text-[var(--color-text)]" />
                        <span className="text-xl font-bold tracking-tighter border-l border-[var(--card-border)] pl-3">PARTNER</span>
                    </div>
                    <button
                        onClick={() => navigate(-1)}
                        className="text-[var(--color-brand)] hover:opacity-80 font-bold uppercase tracking-widest text-xs transition-opacity"
                    >
                        ← Back
                    </button>
                </div>

                <div className="bg-[var(--card-bg)] border border-[var(--card-border)] rounded-3xl p-8 md:p-12 shadow-xl">
                    <h1 className="text-4xl font-black mb-4 tracking-tighter">Privacy Policy</h1>
                    <p className="text-[var(--color-text-muted)] mb-12 font-medium">For Network Partners & Creators • Last Updated: March 31, 2026</p>

                    <section className="space-y-10">
                        <div>
                            <h2 className="text-2xl font-bold text-[var(--color-brand)] mb-4">1. Data Privacy for Partners</h2>
                            <p className="leading-relaxed opacity-90">As a Creator or Network Partner, you trust us with your identity and audience metrics. We handle your data with high-fidelity security to ensure your commissions and attribution are protected.</p>
                        </div>

                        <div>
                            <h2 className="text-2xl font-bold text-[var(--color-brand)] mb-4">2. Attribution & Payout Data</h2>
                            <p className="mb-4 leading-relaxed opacity-90">We collect and process data specifically to verify your contributions to the network:</p>
                            <ul className="list-disc pl-6 space-y-3 text-[var(--color-text-muted)]">
                                <li><strong className="text-[var(--color-text)]">Link Telemetry:</strong> We track clicks and conversion events generated by your "Smart Pass" tracking links.</li>
                                <li><strong className="text-[var(--color-text)]">Payout Identity:</strong> We securely store your bank or ledger information to facilitate rolling Net-30 commission payments.</li>
                                <li><strong className="text-[var(--color-text)]">Profile Metrics:</strong> We track your "Velocity Tiers" to unlock achievement bonuses and retention rewards.</li>
                            </ul>
                        </div>

                        <div>
                            <h2 className="text-2xl font-bold text-[var(--color-brand)] mb-4">3. Audience Protection</h2>
                            <p className="leading-relaxed opacity-90 text-[var(--color-text-muted)]">Mojipass® does not scrape or store identifiable shopper data from your audience beyond what is required for attribution verification. We never sell your audience insights to third-party advertisers.</p>
                        </div>

                        <div className="pt-12 border-t border-[var(--card-border)]">
                            <p className="text-sm text-[var(--color-text-muted)]">Privacy Support: <span className="text-[var(--color-brand)] font-bold">privacy@mojipass.com</span></p>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    );
}
